# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        avatar:
            quality: 75
            filters:
                thumbnail:
                    size: [128, 128]
                    mode: outbound

        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [348, 330]
                    position: center
                    mode: outbound
        
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [800, 530]
                    mode: outbound

        home_avatar:
            quality: 75
            filters:
                thumbnail:
                    size: [24, 24]
                    mode: outbound

        ad_booked_img:
            quality: 75
            filters:
                thumbnail:
                    size: [348, 200]
                    mode: outbound