vich_uploader:
    db_driver: orm

    mappings:
        ad_image:
            uri_prefix: /images/ads
            upload_destination: '%kernel.project_dir%/public/images/ads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        profilPicture_image:
            uri_prefix: /images/profil_pictures
            upload_destination: '%kernel.project_dir%/public/images/profil_pictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
